"""Facility-code → (state, county) lookup."""

from __future__ import annotations

import re
from typing import NamedTuple


class CountyHit(NamedTuple):
    state_abbr: str
    county_name: str
    source: str


KNOWN_FACILITY_CODES: dict[str, tuple[str, str]] = {
    "PIC": ("TX", "Cameron"),
    "PIRGS": ("TX", "Cameron"),
    "RGS": ("TX", "Hidalgo"),
    "RGRNDTX": ("TX", "Webb"),
    "LRDICDF": ("TX", "Webb"),
    "LRDHOLD": ("TX", "Webb"),
    "LRDMCTX": ("TX", "Webb"),
    "EHDLGTX": ("TX", "Hidalgo"),
    "ELVDFTX": ("TX", "Willacy"),
    "WCRDFTX": ("TX", "Willacy"),
    "VALVETX": ("TX", "Val Verde"),
    "BROKSTX": ("TX", "Brooks"),
    "BSCORTX": ("TX", "Brooks"),
    "BSFLTTX": ("TX", "Brooks"),
    "HSF": ("TX", "Cameron"),
    "HLGHOLD": ("TX", "Cameron"),
    "HMCHOTX": ("TX", "Cameron"),
    "HRLGNTX": ("TX", "Cameron"),
    "VBHOSTX": ("TX", "Cameron"),
    "PTISBTX": ("TX", "Cameron"),
    "LSFHOLD": ("TX", "Cameron"),
    "LFRESTX": ("TX", "Cameron"),
    "SBNTOTX": ("TX", "Cameron"),
    "BRWNSTX": ("TX", "Cameron"),
    "MRCDSTX": ("TX", "Hidalgo"),
    "EDNBGTX": ("TX", "Hidalgo"),
    "MCAHOLD": ("TX", "Hidalgo"),
    "PLMVWTX": ("TX", "Hidalgo"),
    "ALAMOTX": ("TX", "Hidalgo"),
    "HDLGOTX": ("TX", "Hidalgo"),
    "SJUANTX": ("TX", "Hidalgo"),
    "LAFERTX": ("TX", "Cameron"),
    "WESLTX": ("TX", "Hidalgo"),
    "SP8WWTX": ("TX", "Hidalgo"),
    "HISMCTX": ("TX", "Hidalgo"),
    "LCIMCTX": ("TX", "Hidalgo"),
    "HTLPPTX": ("TX", "Hidalgo"),
    "RGHOSTX": ("TX", "Hidalgo"),
    "HIDALTX": ("TX", "Hidalgo"),
    "SPIPDTX": ("TX", "Cameron"),
    "STDHOLD": ("TX", "Frio"),
    "STCDFTX": ("TX", "Frio"),
    "STFRCTX": ("TX", "Frio"),
    "TASTDTX": ("TX", "Frio"),
    "TAKARTX": ("TX", "Karnes"),
    "KRNRCTX": ("TX", "Karnes"),
    "KCCDCTX": ("TX", "Karnes"),
    "KARNETX": ("TX", "Karnes"),
    "KINNETX": ("TX", "Kinney"),
    "POLKCTX": ("TX", "Polk"),
    "JCRLYTX": ("TX", "Montgomery"),
    "MTGPCTX": ("TX", "Montgomery"),
    "MONTGTX": ("TX", "Montgomery"),
    "MTGHOLD": ("TX", "Montgomery"),
    "HCAHCTX": ("TX", "Montgomery"),
    "HUNMHTX": ("TX", "Walker"),
    "HOUICDF": ("TX", "Harris"),
    "HOUHOLD": ("TX", "Harris"),
    "HOUGTTX": ("TX", "Harris"),
    "IAHSFTX": ("TX", "Harris"),
    "HARRIGA": ("GA", "Harris"),
    "HHBTHTX": ("TX", "Harris"),
    "HCPSYTX": ("TX", "Harris"),
    "MEMRHFL": ("FL", "Broward"),
    "MHNHHTX": ("TX", "Harris"),
    "EPC": ("TX", "El Paso"),
    "EPCJUVI": ("TX", "El Paso"),
    "EPCDFTX": ("TX", "El Paso"),
    "EPLTATX": ("TX", "El Paso"),
    "EPBHSTX": ("TX", "El Paso"),
    "TNGLPOE": ("TX", "El Paso"),
    "TORHOLD": ("TX", "El Paso"),
    "DSMCNTX": ("TX", "El Paso"),
    "UMCEPTX": ("TX", "El Paso"),
    "RDHEATX": ("TX", "El Paso"),
    "HSEPTX": ("TX", "El Paso"),
    "CSHEPTX": ("TX", "El Paso"),
    "CISAETX": ("TX", "El Paso"),
    "HISEPTX": ("TX", "El Paso"),
    "HSELPTX": ("TX", "El Paso"),
    "HIELPTX": ("TX", "El Paso"),
    "RAMEPTX": ("TX", "El Paso"),
    "ELPCOTX": ("TX", "El Paso"),
    "WTXDFTX": ("TX", "Hudspeth"),
    "HUDSPTX": ("TX", "Hudspeth"),
    "BOPLTL": ("TX", "El Paso"),
    "EPCPCTX": ("TX", "El Paso"),
    "DALHOLD": ("TX", "Dallas"),
    "DALCOTX": ("TX", "Dallas"),
    "EULESTX": ("TX", "Tarrant"),
    "BEDCITX": ("TX", "Tarrant"),
    "JOHNSTX": ("TX", "Johnson"),
    "PRLDCTX": ("TX", "Johnson"),
    "PRLHOLD": ("TX", "Johnson"),
    "JHRWLTX": ("TX", "McLennan"),
    "WCTHOLD": ("TX", "McLennan"),
    "WACLATX": ("TX", "Bexar"),
    "MCCLETX": ("TX", "McLennan"),
    "RNDLLTX": ("TX", "Randall"),
    "AMTHOLD": ("TX", "Potter"),
    "LBKHOLD": ("TX", "Lubbock"),
    "LUBBOTX": ("TX", "Lubbock"),
    "ABTHOLD": ("TX", "Taylor"),
    "ABRMCTX": ("TX", "Taylor"),
    "TAYLOTX": ("TX", "Taylor"),
    "WINCOTX": ("TX", "Winkler"),
    "MIDLATX": ("TX", "Midland"),
    "MLDHOLD": ("TX", "Midland"),
    "BSTAYTX": ("TX", "Williamson"),
    "BSWRRTX": ("TX", "Williamson"),
    "ANSGHTX": ("TX", "Jones"),
    "ECLECTX": ("TX", "Ector"),
    "ODESSTX": ("TX", "Ector"),
    "ECTORTX": ("TX", "Ector"),
    "BURNETX": ("TX", "Burnet"),
    "PECOSTX": ("TX", "Reeves"),
    "REDETTX": ("TX", "Reeves"),
    "REJUVTX": ("TX", "Reeves"),
    "DRCPCTX": ("TX", "Val Verde"),
    "DLRHOLD": ("TX", "Val Verde"),
    "EDNDCTX": ("TX", "Concho"),
    "EDNHOLD": ("TX", "Concho"),
    "EDCHOLD": ("TX", "Concho"),
    "SAGHOLD": ("TX", "Tom Green"),
    "SAGRSTX": ("TX", "Tom Green"),
    "TGREETX": ("TX", "Tom Green"),
    "SHNMCTX": ("TX", "Tom Green"),
    "GRYLATX": ("TX", "Grayson"),
    "GUADATX": ("TX", "Guadalupe"),
    "BSQUETX": ("TX", "Bosque"),
    "FREESTX": ("TX", "Freestone"),
    "BELCOTX": ("TX", "Bell"),
    "MAVERTX": ("TX", "Maverick"),
    "MARTNTX": ("TX", "Martin"),
    "FRIOCTX": ("TX", "Frio"),
    "SMRVLTX": ("TX", "Somervell"),
    "ANDRWTX": ("TX", "Andrews"),
    "CULBETX": ("TX", "Culberson"),
    "CRYCCTX": ("TX", "Zavala"),
    "VICTOTX": ("TX", "Victoria"),
    "CCCSSTX": ("TX", "Nueces"),
    "CRPHOLD": ("TX", "Nueces"),
    "CBENDTX": ("TX", "Nueces"),
    "TVMSATX": ("TX", "Bexar"),
    "MSTHSTX": ("TX", "Bexar"),
    "OKMHKTX": ("TX", "Karnes"),
    "BMCSATX": ("TX", "Bexar"),
    "BWMARCA": ("CA", "Monterey"),
    "FRIRHTX": ("TX", "Frio"),
    "PTISATX": ("TX", "Bexar"),
    "PRESITX": ("TX", "Presidio"),
    "WARCOTX": ("TX", "Ward"),
    "DRHCSTX": ("TX", "Dimmit"),
    "JEFFETX": ("TX", "Jefferson"),
    "WAYNENY": ("NY", "Wayne"),
    "HARDJIA": ("IA", "Hardin"),
    "VRK": ("NY", "New York"),
    "BTV": ("NY", "Genesee"),
    "CMDHOLD": ("NY", "Genesee"),
    "BUFHOLD": ("NY", "Erie"),
    "NYCHOLD": ("NY", "New York"),
    "JFKTSNY": ("NY", "Queens"),
    "JHMCJNY": ("NY", "Queens"),
    "QUEHONY": ("NY", "Queens"),
    "BEHOSNY": ("NY", "New York"),
    "ISHOSNY": ("NY", "New York"),
    "KCHOSNY": ("NY", "Kings"),
    "BXCHSNY": ("NY", "Bronx"),
    "BOPBRO": ("NY", "Kings"),
    "ALBHOLD": ("NY", "Albany"),
    "ALBCONY": ("NY", "Albany"),
    "ONONDNY": ("NY", "Onondaga"),
    "RENSSNY": ("NY", "Rensselaer"),
    "CIPHOLD": ("NY", "Suffolk"),
    "CHMCINY": ("NY", "Suffolk"),
    "SUFFONY": ("NY", "Suffolk"),
    "NASSANY": ("NY", "Nassau"),
    "ORANGNY": ("NY", "Orange"),
    "OGRMCNY": ("NY", "Orange"),
    "NWHNVNC": ("NC", "New Hanover"),
    "WHITFGA": ("GA", "Whitfield"),
    "ALLEGNY": ("NY", "Allegany"),
    "WAYNNY": ("NY", "Wayne"),
    "BROMMNY": ("NY", "Broome"),
    "JEFFENY": ("NY", "Jefferson"),
    "LIVINNY": ("NY", "Livingston"),
    "ONECONY": ("NY", "Oneida"),
    "LEWISNY": ("NY", "Lewis"),
    "TIOGANY": ("NY", "Tioga"),
    "CAYUGNY": ("NY", "Cayuga"),
    "CATTANY": ("NY", "Cattaraugus"),
    "WYMCONY": ("NY", "Wyoming"),
    "GENESNY": ("NY", "Genesee"),
    "YATESNY": ("NY", "Yates"),
    "STEUBNY": ("NY", "Steuben"),
    "WASCONY": ("NY", "Washington"),
    "STLAWNY": ("NY", "St. Lawrence"),
    "CHEMUNY": ("NY", "Chemung"),
    "CHENANY": ("NY", "Chenango"),
    "MADISNY": ("NY", "Madison"),
    "ECMCBNY": ("NY", "Erie"),
    "NYULSTC": ("NY", "Ulster"),
    "NYBUFFC": ("NY", "Erie"),
    "NYFISHC": ("NY", "Dutchess"),
    "NYEASTC": ("NY", "Ulster"),
    "NYGREAC": ("NY", "Washington"),
    "NYGROVC": ("NY", "Livingston"),
    "NYMARCC": ("NY", "Oneida"),
    "NYMOHOC": ("NY", "Oneida"),
    "NYORLNC": ("NY", "Orleans"),
    "NYMDSTC": ("NY", "Oneida"),
    "NYOGDNC": ("NY", "St. Lawrence"),
    "NYLIVIC": ("NY", "Livingston"),
    "NYADIRC": ("NY", "Essex"),
    "CSYJVNY": ("NY", "New York"),
    "ELZICDF": ("NJ", "Union"),
    "ESSEXNJ": ("NJ", "Essex"),
    "HUDSONJ": ("NJ", "Hudson"),
    "BERGENJ": ("NJ", "Bergen"),
    "MONMONJ": ("NJ", "Monmouth"),
    "DHDFNJ": ("NJ", "Essex"),
    "MLJHOLD": ("NJ", "Burlington"),
    "SUSSENJ": ("NJ", "Sussex"),
    "SALEMNJ": ("NJ", "Salem"),
    "TRRMCNJ": ("NJ", "Union"),
    "AKPSYNJ": ("NJ", "Mercer"),
    "JYCMCNJ": ("NJ", "Hudson"),
    "HACMCNJ": ("NJ", "Bergen"),
    "UNIVHNJ": ("NJ", "Essex"),
    "BOPFAI": ("NJ", "Cumberland"),
    "YORCOPA": ("PA", "York"),
    "YRKHOLD": ("PA", "York"),
    "PIKCOPA": ("PA", "Pike"),
    "PKCNTPA": ("PA", "Pike"),
    "PKEHOLD": ("PA", "Pike"),
    "CLINTPA": ("PA", "Clinton"),
    "CAMBRPA": ("PA", "Cambria"),
    "BERKSPA": ("PA", "Berks"),
    "BRKHOLD": ("PA", "Berks"),
    "BCORCPA": ("PA", "Berks"),
    "BEFAMPA": ("PA", "Berks"),
    "BESECPA": ("PA", "Berks"),
    "BEJUVPA": ("PA", "Berks"),
    "BEAVRPA": ("PA", "Beaver"),
    "LACKAPA": ("PA", "Lackawanna"),
    "LEHIGPA": ("PA", "Lehigh"),
    "DAUPHPA": ("PA", "Dauphin"),
    "DELAWPA": ("PA", "Delaware"),
    "ERICOPA": ("PA", "Erie"),
    "LAWREPA": ("PA", "Lawrence"),
    "ALLEGPA": ("PA", "Allegheny"),
    "PITHOLD": ("PA", "Allegheny"),
    "PHIHOLD": ("PA", "Philadelphia"),
    "MSVPCPA": ("PA", "Clearfield"),
    "BOPMVC": ("PA", "Clearfield"),
    "MVPNHPA": ("PA", "Clearfield"),
    "CARBOPA": ("PA", "Carbon"),
    "COLUMPA": ("PA", "Columbia"),
    "MTNITPA": ("PA", "Centre"),
    "MONTGPA": ("PA", "Montgomery"),
    "BOPCAA": ("PA", "Wayne"),
    "HRREGVA": ("VA", "Portsmouth city"),
    "CARDFVA": ("VA", "Caroline"),
    "FRMVLVA": ("VA", "Prince Edward"),
    "RAPPSVA": ("VA", "Stafford"),
    "PWILLVA": ("VA", "Prince William"),
    "FAICOVA": ("VA", "Fairfax"),
    "FXADCVA": ("VA", "Fairfax"),
    "RICHMVA": ("VA", "Richmond city"),
    "RCMHOLD": ("VA", "Richmond city"),
    "ROANOVA": ("VA", "Roanoke city"),
    "RMKHOLD": ("VA", "Roanoke city"),
    "RONKEVA": ("VA", "Roanoke city"),
    "ALEXAVA": ("VA", "Alexandria city"),
    "NORFOVA": ("VA", "Norfolk city"),
    "NORHOLD": ("VA", "Norfolk city"),
    "VIRBEVA": ("VA", "Virginia Beach city"),
    "WTREGVA": ("VA", "Suffolk city"),
    "VPREGVA": ("VA", "Williamsburg city"),
    "RSREGVA": ("VA", "Prince George"),
    "NRREGVA": ("VA", "Loudoun"),
    "ALBEMVA": ("VA", "Albemarle"),
    "ROCKIVA": ("VA", "Rockingham"),
    "HBGHOLD": ("VA", "Harrisonburg city"),
    "MWASHVA": ("VA", "Fredericksburg city"),
    "MRREGVA": ("VA", "Augusta"),
    "CSSCHVA": ("VA", "Prince Edward"),
    "WVIRGVA": ("VA", "Roanoke"),
    "NRJDCVA": ("VA", "Roanoke"),
    "CVREGVA": ("VA", "Orange"),
    "NVJDCVA": ("VA", "Fairfax"),
    "NNREGVA": ("VA", "Warsaw"),
    "LOUCOVA": ("VA", "Loudoun"),
    "CHFLDVA": ("VA", "Chesterfield"),
    "CULPEVA": ("VA", "Culpeper"),
    "WVSCENT": ("WV", "Kanawha"),
    "WVNORTH": ("WV", "Marshall"),
    "WVEASTR": ("WV", "Berkeley"),
    "WVREGWV": ("WV", "Berkeley"),
    "CENTRWV": ("WV", "Braxton"),
    "BOPMRG": ("WV", "Monongalia"),
    "WORCEMD": ("MD", "Worcester"),
    "HOWARMD": ("MD", "Howard"),
    "FREDEMD": ("MD", "Frederick"),
    "FRDHOLD": ("MD", "Frederick"),
    "FCOHOLD": ("MD", "Frederick"),
    "DORCHMD": ("MD", "Dorchester"),
    "AAORDMD": ("MD", "Anne Arundel"),
    "CARROMD": ("MD", "Carroll"),
    "BALHOLD": ("MD", "Baltimore city"),
    "DIIHBMD": ("MD", "Baltimore city"),
    "DCDOCDC": ("DC", "District of Columbia"),
    "WASHOLD": ("DC", "District of Columbia"),
    "DECCSMY": ("DE", "Sussex"),
    "SUSSEDE": ("DE", "Sussex"),
    "DVDHOLD": ("DE", "Kent"),
    "BPC": ("MA", "Suffolk"),
    "BOSHOLD": ("MA", "Suffolk"),
    "BIDHPMA": ("MA", "Suffolk"),
    "SUFFOMA": ("MA", "Suffolk"),
    "BRINDMA": ("MA", "Bristol"),
    "PLYMOMA": ("MA", "Plymouth"),
    "GREENMA": ("MA", "Franklin"),
    "HAMPDMA": ("MA", "Hampden"),
    "BARNSMA": ("MA", "Barnstable"),
    "NORFOMA": ("MA", "Norfolk"),
    "MABSHOS": ("MA", "Plymouth"),
    "MATEWKS": ("MA", "Middlesex"),
    "MATSHOS": ("MA", "Bristol"),
    "LSHOSMA": ("MA", "Suffolk"),
    "HOTELMA": ("MA", "Suffolk"),
    "NASHUMA": ("MA", "Suffolk"),
    "WYATTRI": ("RI", "Providence"),
    "RICRANS": ("RI", "Providence"),
    "MIRHPRI": ("RI", "Providence"),
    "HARFOCT": ("CT", "Hartford"),
    "HARHOLD": ("CT", "Hartford"),
    "CTLAFSL": ("CT", "Hartford"),
    "CUMBEME": ("ME", "Cumberland"),
    "POMHOLD": ("ME", "Cumberland"),
    "MEYTHCT": ("ME", "Cumberland"),
    "PISCAME": ("ME", "Piscataquis"),
    "AROOSME": ("ME", "Aroostook"),
    "PENOBME": ("ME", "Penobscot"),
    "SOMERME": ("ME", "Somerset"),
    "YORKCME": ("ME", "York"),
    "STRAFNH": ("NH", "Strafford"),
    "MANHOLD": ("NH", "Hillsborough"),
    "COOCONH": ("NH", "Coos"),
    "ROCKINH": ("NH", "Rockingham"),
    "WWDHDNH": ("NH", "Strafford"),
    "VTSTALB": ("VT", "Franklin"),
    "STAHOLD": ("VT", "Franklin"),
    "VTCHTDN": ("VT", "Chittenden"),
    "VTDCORR": ("VT", "Washington"),
    "FRACOVT": ("VT", "Franklin"),
    "ADDCOVT": ("VT", "Addison"),
    "KRO": ("FL", "Miami-Dade"),
    "KROHOLD": ("FL", "Miami-Dade"),
    "KRHUBFL": ("FL", "Miami-Dade"),
    "MIAHOLD": ("FL", "Broward"),
    "MSF": ("FL", "Broward"),
    "WCCPBFL": ("FL", "Broward"),
    "BROCRFL": ("FL", "Broward"),
    "BROJAFL": ("FL", "Broward"),
    "BRGMCFL": ("FL", "Broward"),
    "FLBHCFL": ("FL", "Broward"),
    "FLHOSFL": ("FL", "Broward"),
    "ASHRSFL": ("FL", "Broward"),
    "PWHOSFL": ("FL", "Palm Beach"),
    "PALMBFL": ("FL", "Palm Beach"),
    "LAKMCFL": ("FL", "Palm Beach"),
    "LRKNHFL": ("FL", "Miami-Dade"),
    "LRKBHFL": ("FL", "Miami-Dade"),
    "JMHOSFL": ("FL", "Miami-Dade"),
    "UMIAHFL": ("FL", "Miami-Dade"),
    "BOPMIM": ("FL", "Miami-Dade"),
    "BOPMIA": ("FL", "Miami-Dade"),
    "MERCYFL": ("FL", "Miami-Dade"),
    "WMDBHFL": ("FL", "Miami-Dade"),
    "PMHOSFL": ("FL", "Miami-Dade"),
    "WKBHMFL": ("FL", "Miami-Dade"),
    "CKHOSFL": ("FL", "Miami-Dade"),
    "METROFL": ("FL", "Miami-Dade"),
    "CEMEDFL": ("FL", "Miami-Dade"),
    "NBRMCFL": ("FL", "Broward"),
    "NFMIGFL": ("FL", "Miami-Dade"),
    "GLADEFL": ("FL", "Glades"),
    "COLLIFL": ("FL", "Collier"),
    "HRCMCFL": ("FL", "Collier"),
    "BAKERFL": ("FL", "Baker"),
    "FLBAKCI": ("FL", "Baker"),
    "ORLHOLD": ("FL", "Orange"),
    "ORANGFL": ("FL", "Orange"),
    "HCAFMFL": ("FL", "Duval"),
    "JAXHOLD": ("FL", "Duval"),
    "TAMHOLD": ("FL", "Hillsborough"),
    "PINELFL": ("FL", "Pinellas"),
    "TALHOLD": ("FL", "Leon"),
    "PUTMAFL": ("FL", "Putnam"),
    "STJONFL": ("FL", "St. Johns"),
    "MARTIFL": ("FL", "Martin"),
    "STUHOLD": ("FL", "Martin"),
    "HENDRFL": ("FL", "Hendry"),
    "HNRMCFL": ("FL", "Hendry"),
    "FMYHOLD": ("FL", "Lee"),
    "MNRMCFL": ("FL", "Broward"),
    "MONROFL": ("FL", "Monroe"),
    "LRKMCFL": ("FL", "Monroe"),
    "WAKULFL": ("FL", "Wakulla"),
    "BRDFDFL": ("FL", "Bradford"),
    "COLUMFL": ("FL", "Columbia"),
    "HARDEFL": ("FL", "Hardee"),
    "SUWANFL": ("FL", "Suwannee"),
    "LEVYCFL": ("FL", "Levy"),
    "CHRLTFL": ("FL", "Charlotte"),
    "MANATFL": ("FL", "Manatee"),
    "BRADEFL": ("FL", "Manatee"),
    "HERNAFL": ("FL", "Hernando"),
    "EFMHMFL": ("FL", "Baker"),
    "FLBREVC": ("FL", "Brevard"),
    "FLDADCI": ("FL", "Miami-Dade"),
    "FLMARIC": ("FL", "Marion"),
    "FLSPSTA": ("FL", "Bradford"),
    "BOPCNV": ("TN", "Davidson"),
    "STWRTGA": ("GA", "Stewart"),
    "IRWINGA": ("GA", "Irwin"),
    "FIPCMGA": ("GA", "Charlton"),
    "JAMESGA": ("GA", "Charlton"),
    "FIPCAGA": ("GA", "Charlton"),
    "ATLHOLD": ("GA", "Fulton"),
    "ATLANGA": ("GA", "Fulton"),
    "GMHATGA": ("GA", "Fulton"),
    "RADDFGA": ("GA", "Henry"),
    "NGDCTGA": ("GA", "Hall"),
    "HASHENE": ("GA", "Hall"),
    "HALLJGA": ("GA", "Hall"),
    "WHITFGA": ("GA", "Whitfield"),
    "FLOYDGA": ("GA", "Floyd"),
    "COBBJGA": ("GA", "Cobb"),
    "DEKABGA": ("GA", "DeKalb"),
    "BARTOGA": ("GA", "Bartow"),
    "GWINNGA": ("GA", "Gwinnett"),
    "CHATHGA": ("GA", "Chatham"),
    "BOPRAE": ("GA", "Telfair"),
    "GADRYJM": ("GA", "Charlton"),
    "JENATLA": ("LA", "Rapides"),
    "JENADLA": ("LA", "LaSalle"),
    "BASILLA": ("LA", "Acadia"),
    "SNDHOLD": ("CA", "San Diego"),
    "SNJHOLD": ("CA", "San Diego"),
    "CCAHUTX": ("TX", "Williamson"),
    "IWAHOLD": ("AZ", "Maricopa"),
    "FCLT8CA": ("CA", "San Diego"),
    "LQWCSTX": ("TX", "Frio"),
    "SUPHDTX": ("TX", "Webb"),
    "COMFTFL": ("FL", "Miami-Dade"),
    "GUDOCHG": ("GU", "Guam"),
    "CHAHOLD": ("VI", "St. Thomas"),
    "APIBHCA": ("CA", "San Diego"),
    "SAIHOLD": ("MP", "Saipan"),
    "MPSIPAN": ("MP", "Saipan"),
    "LTVHOLD": ("VA", "Fairfax"),
    "SALHOLD": ("MD", "Wicomico"),
    "SAJHOLD": ("PR", "San Juan"),
    "SJUHOLD": ("PR", "Carolina"),
    "BOPGUA": ("PR", "Guaynabo"),
    "SJS": ("PR", "Bayamon"),
    "HCAFCC": ("FL", "Miami-Dade"),
    "ANCHOAK": ("AK", "Anchorage"),
    "AKCOOKI": ("AK", "Anchorage"),
    "ANCHOLD": ("AK", "Anchorage"),
    "PINEPLA": ("LA", "Evangeline"),
    "RWCCMLA": ("LA", "Ouachita"),
    "LAWINCI": ("LA", "Winn"),
    "OLACCLA": ("LA", "Catahoula"),
    "TENSALA": ("LA", "Tensas"),
    "CATAHLA": ("LA", "Catahoula"),
    "BOSSRLA": ("LA", "Bossier"),
    "JKPCCLA": ("LA", "Jackson"),
    "APPSCLA": ("LA", "Allen"),
    "RVRCCLA": ("LA", "Concordia"),
    "CONCOLA": ("LA", "Concordia"),
    "BOPOAD": ("LA", "Allen"),
    "AVPARLA": ("LA", "Avoyelles"),
    "ORPARLA": ("LA", "Orleans"),
    "STTAMLA": ("LA", "St. Tammany"),
    "NATCHLA": ("LA", "Natchitoches"),
    "USMWDLA": ("LA", "Caddo"),
    "VVSHOLD": ("LA", "Caddo"),
    "LKLNDLA": ("LA", "Caddo"),
    "CSANOLA": ("LA", "Rapides"),
    "HIRAYTX": ("TX", "Frio"),
    "CISEPTX": ("TX", "El Paso"),
    "CSCLQTX": ("TX", "Frio"),
    "BWEPATX": ("TX", "Frio"),
    "HAVACTX": ("TX", "Frio"),
    "WINWYAZ": ("AZ", "Pinal"),
    "QLTYSCA": ("CA", "Imperial"),
    "HESPCAZ": ("AZ", "Pima"),
    "ALESSAZ": ("AZ", "Maricopa"),
    "NOLHOLD": ("LA", "Orleans"),
    "ADAMSMS": ("MS", "Adams"),
    "TALLAMS": ("MS", "Tallahatchie"),
    "MADISMS": ("MS", "Madison"),
    "HCPSCMS": ("MS", "Hancock"),
    "JAKHOLD": ("MS", "Hinds"),
    "USMSDMS": ("MS", "Hinds"),
    "ETOWAAL": ("AL", "Etowah"),
    "ETWHOLD": ("AL", "Etowah"),
    "DEKALAL": ("AL", "DeKalb"),
    "BALDWAL": ("AL", "Baldwin"),
    "PCKNSAL": ("AL", "Pickens"),
    "MNTGMAL": ("AL", "Montgomery"),
    "MONCJAL": ("AL", "Montgomery"),
    "BHMHOLD": ("AL", "Jefferson"),
    "MONTGAL": ("AL", "Montgomery"),
    "ALEXAAL": ("AL", "Cleburne"),
    # Actually I'm not sure about Alexandria AL - leaving as is
    "CHARLSC": ("SC", "Charleston"),
    "CHLHOLD": ("SC", "Charleston"),
    "DORCDSC": ("SC", "Dorchester"),
    "LEXINSC": ("SC", "Lexington"),
    "YORCOSC": ("SC", "York"),
    "ANDERSC": ("SC", "Anderson"),
    "PCKSNAL": ("AL", "Pickens"),
    "COAHOLD": ("SC", "Richland"),
    "COLCASC": ("SC", "Lexington"),
    "MECKLNC": ("NC", "Mecklenburg"),
    "CLTHOLD": ("NC", "Mecklenburg"),
    "CBRRSNC": ("NC", "Cabarrus"),
    "ALAMCNC": ("NC", "Alamance"),
    "GASTNNC": ("NC", "Gaston"),
    "HENDENC": ("NC", "Henderson"),
    "FORSYNC": ("NC", "Forsyth"),
    "WAKECNC": ("NC", "Wake"),
    "RDUHOLD": ("NC", "Wake"),
    "ASHECNC": ("NC", "Ashe"),
    "TNWESDF": ("TN", "Hardeman"),
    "DAVIDTN": ("TN", "Davidson"),
    "KNXDFTN": ("TN", "Knox"),
    "KNXHOLD": ("TN", "Knox"),
    "SILERTN": ("TN", "Hamilton"),
    "MEMHOLD": ("TN", "Shelby"),
    "JACKSTN": ("TN", "Madison"),
    "CNGHOLD": ("TN", "Hamilton"),
    "BOONEKY": ("KY", "Boone"),
    "OLDHAKY": ("KY", "Oldham"),
    "FAYETKY": ("KY", "Fayette"),
    "LEXFCKY": ("KY", "Fayette"),
    "GRAYSKY": ("KY", "Grayson"),
    "GRYDCKY": ("KY", "Grayson"),
    "ADAIRKY": ("KY", "Adair"),
    "LOUHOLD": ("KY", "Jefferson"),
    "BOPLEX": ("KY", "Fayette"),
    "MOROWOH": ("OH", "Morrow"),
    "BUTLEOH": ("OH", "Butler"),
    "GEAUGOH": ("OH", "Geauga"),
    "UHGMCOH": ("OH", "Geauga"),
    "SENECOH": ("OH", "Seneca"),
    "PICKJOH": ("OH", "Pickaway"),
    "MAHONOH": ("OH", "Mahoning"),
    "BEDFOOH": ("OH", "Cuyahoga"),
    "MAPLEOH": ("OH", "Cuyahoga"),
    "CCANOOH": ("OH", "Mahoning"),
    "BOPNEO": ("OH", "Mahoning"),
    "CLEHOLD": ("OH", "Cuyahoga"),
    "CINHOLD": ("OH", "Hamilton"),
    "CLMHOLD": ("OH", "Franklin"),
    "MNROEMI": ("MI", "Monroe"),
    "CALHOMI": ("MI", "Calhoun"),
    "MSKGNMI": ("MI", "Muskegon"),
    "ELKHAIN": ("IN", "Elkhart"),
    "WASHTMI": ("MI", "Washtenaw"),
    "STCLAMI": ("MI", "St. Clair"),
    "DETHOLD": ("MI", "Wayne"),
    "DEAPDMI": ("MI", "Wayne"),
    "BHFLDMI": ("MI", "Kalamazoo"),
    "MLPHHMI": ("MI", "St. Clair"),
    "GRMHOLD": ("MI", "Kent"),
    "KENTCMI": ("MI", "Kent"),
    "CHIPPMI": ("MI", "Chippewa"),
    "SAMBCMI": ("MI", "Wayne"),
    "MIWPRPH": ("MI", "Wayne"),
    "BRANCMI": ("MI", "Branch"),
    "SSMHOLD": ("MI", "Chippewa"),
    "WIDODGE": ("WI", "Dodge"),
    "DODGEWI": ("WI", "Dodge"),
    "KENOSWI": ("WI", "Kenosha"),
    "BROWNWI": ("WI", "Brown"),
    "WAUKEWI": ("WI", "Waukesha"),
    "FNDDUWI": ("WI", "Fond du Lac"),
    "DOUGLWI": ("WI", "Douglas"),
    "MILHOLD": ("WI", "Milwaukee"),
    "MCHENIL": ("IL", "McHenry"),
    "KANKEIL": ("IL", "Kankakee"),
    "PULASIL": ("IL", "Pulaski"),
    "TRICOIL": ("IL", "Effingham"),
    "JEFFEIL": ("IL", "Jefferson"),
    "ELGPDIL": ("IL", "Cook"),
    "ROCKIIL": ("IL", "Rock Island"),
    "RIIHOLD": ("IL", "Rock Island"),
    "RCKISIL": ("IL", "Rock Island"),
    "BSAHOLD": ("IL", "Cook"),
    "CHIHOLD": ("IL", "Cook"),
    "CCHHSIL": ("IL", "Cook"),
    "OGLECIL": ("IL", "Ogle"),
    "MERCEIL": ("IL", "Mercer"),
    "HLYCHIL": ("IL", "Cook"),
    "SANJAIL": ("IL", "Sangamon"),
    "ILPICKN": ("IL", "Perry"),
    "REHOSIL": ("IL", "Cook"),
    "PCJDCIL": ("IL", "Peoria"),
    "RRIVRIL": ("IL", "Lee"),
    "KANECIL": ("IL", "Kane"),
    "CNTGRIL": ("IL", "McHenry"),
    "LYOLAIL": ("IL", "Cook"),
    "POTTAIA": ("IA", "Pottawattamie"),
    "MARSHIA": ("IA", "Marshall"),
    "POLKJIA": ("IA", "Polk"),
    "DSMHOLD": ("IA", "Polk"),
    "LINNJIA": ("IA", "Linn"),
    "CRIHOLD": ("IA", "Linn"),
    "STORYIA": ("IA", "Story"),
    "BREMEIA": ("IA", "Bremer"),
    "WOODBIA": ("IA", "Woodbury"),
    "SXCHOLD": ("IA", "Woodbury"),
    "MUSCAIA": ("IA", "Muscatine"),
    "SCOTTIA": ("IA", "Scott"),
    "CHIHMIA": ("IA", "Pottawattamie"),
    "SHERBMN": ("MN", "Sherburne"),
    "CARJAMN": ("MN", "Carver"),
    "CAJUVMN": ("MN", "Carver"),
    "KANDIMN": ("MN", "Kandiyohi"),
    "FREEBMN": ("MN", "Freeborn"),
    "NOBLEMN": ("MN", "Nobles"),
    "RAADCMN": ("MN", "Ramsey"),
    "SPMHOLD": ("MN", "Ramsey"),
    "WAJAIMN": ("MN", "Washington"),
    "NWRCCMN": ("MN", "Polk"),
    "ANWHMMN": ("MN", "Hennepin"),
    "DULHOLD": ("MN", "St. Louis"),
    "MORGNMO": ("MO", "Morgan"),
    "CHRISMO": ("MO", "Christian"),
    "MONTGMO": ("MO", "Montgomery"),
    "LINCOMO": ("MO", "Lincoln"),
    "PLATTMO": ("MO", "Platte"),
    "MISCOMO": ("MO", "Mississippi"),
    "CALDWMO": ("MO", "Caldwell"),
    "SCOTTMO": ("MO", "Scott"),
    "GREENMO": ("MO", "Greene"),
    "STLHOLD": ("MO", "St. Louis city"),
    "KANHOLD": ("MO", "Jackson"),
    "SPGHOLD": ("MO", "Greene"),
    "BOPSPG": ("MO", "Greene"),
    "LRAHOLD": ("AR", "Pulaski"),
    "WASHIAR": ("AR", "Washington"),
    "FAYHOLD": ("AR", "Washington"),
    "FSAHOLD": ("AR", "Sebastian"),
    "SEBASAR": ("AR", "Sebastian"),
    "MILLRAR": ("AR", "Miller"),
    "TXAHOLD": ("AR", "Miller"),
    "LONPDAR": ("AR", "Lonoke"),
    "TULCOOK": ("OK", "Tulsa"),
    "TULHOLD": ("OK", "Tulsa"),
    "OKCHOLD": ("OK", "Oklahoma"),
    "OKCOJOK": ("OK", "Oklahoma"),
    "KCOJFOK": ("OK", "Kay"),
    "GARVIOK": ("OK", "Garvin"),
    "GCLECOK": ("OK", "Grady"),
    "OKMULOK": ("OK", "Okmulgee"),
    "CHEROOK": ("OK", "Cherokee"),
    "CHASEKS": ("KS", "Chase"),
    "SHACOKS": ("KS", "Shawnee"),
    "SHAJUKS": ("KS", "Shawnee"),
    "FINNEKS": ("KS", "Finney"),
    "GCPFCKS": ("KS", "Finney"),
    "RICECKS": ("KS", "Rice"),
    "WICHOLD": ("KS", "Sedgwick"),
    "BUTLEKS": ("KS", "Butler"),
    "OSAHOKS": ("KS", "Miami"),
    "DOCORNE": ("NE", "Douglas"),
    "OMAHOLD": ("NE", "Douglas"),
    "DAKOTNE": ("NE", "Dakota"),
    "PHELPNE": ("NE", "Phelps"),
    "CASSCNE": ("NE", "Cass"),
    "SCOTTNE": ("NE", "Scotts Bluff"),
    "LINCONE": ("NE", "Lincoln"),
    "NRPHOLD": ("NE", "Lincoln"),
    "HASHENE": ("NE", "Hall"),
    "GRIHOLD": ("NE", "Hall"),
    "SARJUNE": ("NE", "Sarpy"),
    "SALINNE": ("NE", "Saline"),
    "DENICDF": ("CO", "Adams"),
    "DENIICO": ("CO", "Adams"),
    "DENVECO": ("CO", "Denver"),
    "DENHOLD": ("CO", "Denver"),
    "DNHMCCO": ("CO", "Denver"),
    "AURORCO": ("CO", "Adams"),
    "ELPASCO": ("CO", "El Paso"),
    "TELLECO": ("CO", "Teller"),
    "PUEHOLD": ("CO", "Pueblo"),
    "PUEBLCO": ("CO", "Pueblo"),
    "GJCHOLD": ("CO", "Mesa"),
    "MESJACO": ("CO", "Mesa"),
    "MOFFECO": ("CO", "Moffat"),
    "CRGHOLD": ("CO", "Moffat"),
    "RIOGRCO": ("CO", "Rio Grande"),
    "ALMHOLD": ("CO", "Alamosa"),
    "ALAMOCO": ("CO", "Alamosa"),
    "PARKJCO": ("CO", "Park"),
    "GSCHOLD": ("CO", "Garfield"),
    "EAGLECO": ("CO", "Eagle"),
    "FREMOCO": ("CO", "Fremont"),
    "DOUGLCO": ("CO", "Douglas"),
    "ARAPACO": ("CO", "Arapahoe"),
    "DURHOLD": ("CO", "La Plata"),
    "LAPLACO": ("CO", "La Plata"),
    "OTEROCO": ("CO", "Otero"),
    "CONEJCO": ("CO", "Conejos"),
    "LDFHOLD": ("CO", "Larimer"),
    "LARIMCO": ("CO", "Larimer"),
    "BRCHOLD": ("CO", "Morgan"),
    "CSDHOLD": ("CO", "El Paso"),
    "UCHUHCO": ("CO", "Denver"),
    "EMBSYCO": ("CO", "Denver"),
    "DRURYCO": ("CO", "Denver"),
    "NATROWY": ("WY", "Natrona"),
    "CSPHOLD": ("WY", "Natrona"),
    "PLATTWY": ("WY", "Platte"),
    "CHYHOLD": ("WY", "Laramie"),
    "LARCOWY": ("WY", "Laramie"),
    "TETONWY": ("WY", "Teton"),
    "SWEETWY": ("WY", "Sweetwater"),
    "FRFLDWY": ("WY", "Laramie"),
    "CASCAMT": ("MT", "Cascade"),
    "BILHOLD": ("MT", "Yellowstone"),
    "YELLOMT": ("MT", "Yellowstone"),
    "FLATHMT": ("MT", "Flathead"),
    "MISSOMT": ("MT", "Missoula"),
    "GALLAMT": ("MT", "Gallatin"),
    "LEWISMT": ("MT", "Lewis and Clark"),
    "DAWSOMT": ("MT", "Dawson"),
    "MUSSEMT": ("MT", "Musselshell"),
    "JEFFEMT": ("MT", "Jefferson"),
    "SHERIMT": ("MT", "Sheridan"),
    "TOOLEMT": ("MT", "Toole"),
    "HILLCMT": ("MT", "Hill"),
    "HAILEID": ("ID", "Twin Falls"),
    "TFALLID": ("ID", "Twin Falls"),
    "TFIHOLD": ("ID", "Twin Falls"),
    "ELMORID": ("ID", "Elmore"),
    "ADACOID": ("ID", "Ada"),
    "BOIHOLD": ("ID", "Ada"),
    "JEFFEID": ("ID", "Jefferson"),
    "IFIHOLD": ("ID", "Bonneville"),
    "BONNEID": ("ID", "Bonneville"),
    "MADISID": ("ID", "Madison"),
    "MINICID": ("ID", "Cassia"),
    "GOODCID": ("ID", "Gooding"),
    "SLSLCUT": ("UT", "Salt Lake"),
    "SLCHOLD": ("UT", "Salt Lake"),
    "CACHEUT": ("UT", "Cache"),
    "WASATUT": ("UT", "Wasatch"),
    "WASHCUT": ("UT", "Washington"),
    "SGUHOLD": ("UT", "Washington"),
    "SUMMIUT": ("UT", "Summit"),
    "TOOELUT": ("UT", "Tooele"),
    "UTAHCUT": ("UT", "Utah"),
    "PRUHOLD": ("UT", "Utah"),
    "WEBERUT": ("UT", "Weber"),
    "OGUHOLD": ("UT", "Weber"),
    "UINTCUT": ("UT", "Uintah"),
    "HENDENV": ("NV", "Clark"),
    "LVGHOLD": ("NV", "Clark"),
    "WASHONV": ("NV", "Washoe"),
    "RENHOLD": ("NV", "Washoe"),
    "NVSDCNV": ("NV", "Nye"),
    "NYEPANV": ("NV", "Nye"),
    "DVHSPNV": ("NV", "Nye"),
    "NOLVGNV": ("NV", "Clark"),
    "HDHSPNV": ("NV", "Clark"),
    "NNVMCNV": ("NV", "Clark"),
    "FSF": ("AZ", "Pinal"),
    "FLO": ("AZ", "Pinal"),
    "EAZ": ("AZ", "Pinal"),
    "CCAFLAZ": ("AZ", "Pinal"),
    "LPLCCAZ": ("AZ", "Pinal"),
    "LPAPSAZ": ("AZ", "Pinal"),
    "CCADCAZ": ("AZ", "Pinal"),
    "PINALAZ": ("AZ", "Pinal"),
    "FLORHAZ": ("AZ", "Pinal"),
    "PHOHOLD": ("AZ", "Maricopa"),
    "MCFAJAZ": ("AZ", "Maricopa"),
    "MCMEDAZ": ("AZ", "Maricopa"),
    "VWHMCAZ": ("AZ", "Maricopa"),
    "STJOSAZ": ("AZ", "Maricopa"),
    "MVMCMAZ": ("AZ", "Maricopa"),
    "AZSPPER": ("AZ", "Maricopa"),
    "AZSPFLO": ("AZ", "Pinal"),
    "BNMCTAZ": ("AZ", "Pima"),
    "TUCHOLD": ("AZ", "Pima"),
    "PIMAJAZ": ("AZ", "Pima"),
    "BOPTCN": ("AZ", "Pima"),
    "BOPTCP": ("AZ", "Pima"),
    "STMARAZ": ("AZ", "Pima"),
    "BOPPHX": ("AZ", "Maricopa"),
    "YUMHOLD": ("AZ", "Yuma"),
    "SLRDCAZ": ("AZ", "Yuma"),
    "LAPAZAZ": ("AZ", "La Paz"),
    "CGRMCAZ": ("AZ", "Pinal"),
    "CAMEDAZ": ("AZ", "Pinal"),
    "BIMDCAZ": ("AZ", "Pinal"),
    "YAVCVAZ": ("AZ", "Yavapai"),
    "YAVAPAZ": ("AZ", "Yavapai"),
    "COCONAZ": ("AZ", "Coconino"),
    "NAVSOAZ": ("AZ", "Navajo"),
    "APACHAZ": ("AZ", "Apache"),
    "GRAHAAZ": ("AZ", "Graham"),
    "COCHIAZ": ("AZ", "Cochise"),
    "SCRUZAZ": ("AZ", "Santa Cruz"),
    "GLEPDCA": ("CA", "Los Angeles"),
    "CHANRAZ": ("AZ", "Maricopa"),
    "AZSVCPC": ("AZ", "Pinal"),
    "OTRPCNM": ("NM", "Otero"),
    "OTROPNM": ("NM", "Otero"),
    "OTERONM": ("NM", "Otero"),
    "TOORANM": ("NM", "Torrance"),
    "CIBOCNM": ("NM", "Cibola"),
    "CIBOLNM": ("NM", "Cibola"),
    "DONAANM": ("NM", "Dona Ana"),
    "MCKINNM": ("NM", "McKinley"),
    "SANDONM": ("NM", "Sandoval"),
    "SANMINM": ("NM", "San Miguel"),
    "SJUANNM": ("NM", "San Juan"),
    "SANTANM": ("NM", "Santa Fe"),
    "SFCORNM": ("NM", "Santa Fe"),
    "LEACONM": ("NM", "Lea"),
    "EDDCONM": ("NM", "Eddy"),
    "CURRYNM": ("NM", "Curry"),
    "CHAVENM": ("NM", "Chaves"),
    "RSWHOLD": ("NM", "Chaves"),
    "ARTSINM": ("NM", "Eddy"),
    "ARTESNM": ("NM", "Eddy"),
    "LASHOLD": ("NM", "Dona Ana"),
    "ABQHOLD": ("NM", "Bernalillo"),
    "PRSHANM": ("NM", "Bernalillo"),
    "HIDALNM": ("NM", "Hidalgo"),
    "CCASDCA": ("CA", "San Diego"),
    "SOBAYCA": ("CA", "San Diego"),
    "SDPROCA": ("CA", "San Diego"),
    "SNDCOCA": ("CA", "San Diego"),
    "SDHOSCA": ("CA", "San Diego"),
    "BOPSDC": ("CA", "San Diego"),
    "WCCSDCA": ("CA", "San Diego"),
    "EMESACA": ("CA", "San Diego"),
    "VISTACA": ("CA", "San Diego"),
    "CASSJCA": ("CA", "San Diego"),
    "BAILECA": ("CA", "San Diego"),
    "JHALLCA": ("CA", "San Diego"),
    "SCVMCCA": ("CA", "San Diego"),
    "PVLYHCA": ("CA", "San Diego"),
    "UCSDHCA": ("CA", "San Diego"),
    "HISDBCA": ("CA", "San Diego"),
    "BWDGICA": ("CA", "San Diego"),
    "CACFMES": ("CA", "Kern"),
    "GLDSACA": ("CA", "Kern"),
    "CADESVI": ("CA", "Kern"),
    "BKLHOLD": ("CA", "Kern"),
    "KERCOCA": ("CA", "Kern"),
    "KERNHCA": ("CA", "Kern"),
    "ADLNTCA": ("CA", "San Bernardino"),
    "SBDHOLD": ("CA", "San Bernardino"),
    "SBERNCA": ("CA", "San Bernardino"),
    "ARRMCCA": ("CA", "San Bernardino"),
    "DSRTVCA": ("CA", "San Bernardino"),
    "VVGMCCA": ("CA", "San Bernardino"),
    "WMHOSCA": ("CA", "Los Angeles"),
    "LANCACA": ("CA", "Los Angeles"),
    "LOSCJCA": ("CA", "Los Angeles"),
    "BARRECA": ("CA", "Los Angeles"),
    "LOSHOLD": ("CA", "Los Angeles"),
    "BOPLOS": ("CA", "Los Angeles"),
    "ALHAMCA": ("CA", "Los Angeles"),
    "BHCALCA": ("CA", "Los Angeles"),
    "POMONCA": ("CA", "Los Angeles"),
    "TEMPLCA": ("CA", "Los Angeles"),
    "PASADCA": ("CA", "Los Angeles"),
    "LPD77CA": ("CA", "Los Angeles"),
    "PLRMCCA": ("CA", "Los Angeles"),
    "PALMDCA": ("CA", "Los Angeles"),
    "TLACYCA": ("CA", "Orange"),
    "MUSIKCA": ("CA", "Orange"),
    "OCIRCCA": ("CA", "Orange"),
    "OCCWJCA": ("CA", "Orange"),
    "WSTMCCA": ("CA", "Orange"),
    "OGCMCCA": ("CA", "Orange"),
    "AGMDCCA": ("CA", "Orange"),
    "COSTACA": ("CA", "Orange"),
    "WESHOLD": ("CA", "Orange"),
    "SAAHOLD": ("CA", "Orange"),
    "SACITCA": ("CA", "Orange"),
    "IRADFCA": ("CA", "Imperial"),
    "ECC": ("CA", "Imperial"),
    "IMPCOCA": ("CA", "Imperial"),
    "IMPHOLD": ("CA", "Imperial"),
    "CADCCAL": ("CA", "Imperial"),
    "VENTUCA": ("CA", "Ventura"),
    "VENHOLD": ("CA", "Ventura"),
    "STMARCA": ("CA", "Ventura"),
    "SBARBCA": ("CA", "Santa Barbara"),
    "BOPLOM": ("CA", "Santa Barbara"),
    "BOPLOF": ("CA", "Santa Barbara"),
    "SLOBICA": ("CA", "San Luis Obispo"),
    "SLJUVCA": ("CA", "San Luis Obispo"),
    "ENLMCCA": ("CA", "Butte"),
    "REDHOLD": ("CA", "Shasta"),
    "CACFDON": ("CA", "San Diego"),
    "SFRHOLD": ("CA", "San Francisco"),
    "RIOCCCA": ("CA", "Sacramento"),
    "SACHOLD": ("CA", "Sacramento"),
    "SACRACA": ("CA", "Sacramento"),
    "CASPSAC": ("CA", "Sacramento"),
    "SCNORCA": ("CA", "Santa Clara"),
    "FRECOCA": ("CA", "Fresno"),
    "FREHOLD": ("CA", "Fresno"),
    "CRMCFCA": ("CA", "Fresno"),
    "YUBAJCA": ("CA", "Yuba"),
    "CONWECA": ("CA", "Contra Costa"),
    "CONCOCA": ("CA", "Contra Costa"),
    "CACFLEO": ("CA", "Yuba"),
    "RIVERCA": ("CA", "Riverside"),
    "CACTYCA": ("CA", "Kern"),
    "CAIRONW": ("CA", "Riverside"),
    "CAWVALL": ("CA", "Riverside"),
    "CAMENCW": ("CA", "San Luis Obispo"),
    "CAMENCE": ("CA", "San Luis Obispo"),
    "CCJAMA": ("CA", "Tehama"),
    "CACCJAM": ("CA", "Tuolumne"),
    "LASWOCA": ("CA", "San Diego"),
    "BPS": ("CA", "Imperial"),
    "STK": ("CA", "San Joaquin"),
    "CSCNWWA": ("WA", "Pierce"),
    "SEAHOLD": ("WA", "King"),
    "BOPSET": ("WA", "King"),
    "FPSSAWA": ("WA", "King"),
    "YIKIMWA": ("WA", "Yakima"),
    "YAKHOLD": ("WA", "Yakima"),
    "CHELAWA": ("WA", "Chelan"),
    "WNTHOLD": ("WA", "Chelan"),
    "OKANOWA": ("WA", "Okanogan"),
    "KITTIWA": ("WA", "Kittitas"),
    "STEVEWA": ("WA", "Stevens"),
    "ECOLOWA": ("WA", "Yakima"),
    "RRFINWA": ("WA", "Yakima"),
    "ADAMSWA": ("WA", "Adams"),
    "COWJVWA": ("WA", "Cowlitz"),
    "FDLHOLD": ("WA", "Whatcom"),
    "BLHHOLD": ("WA", "Whatcom"),
    "SUNNYWA": ("WA", "Yakima"),
    "RICHOLD": ("WA", "Benton"),
    "SPOHOLD": ("WA", "Spokane"),

    "NORCOOR": ("OR", "Umatilla"),
    "NOJUVOR": ("OR", "Wasco"),
    "JOSEPOR": ("OR", "Josephine"),
    "JACKSOR": ("OR", "Jackson"),
    "KLAMCOR": ("OR", "Klamath"),
    "MARICOR": ("OR", "Marion"),
    "LANECOR": ("OR", "Lane"),
    "EUGHOLD": ("OR", "Lane"),
    "COOSCOR": ("OR", "Coos"),
    "DOUGLOR": ("OR", "Douglas"),
    "LINNCOR": ("OR", "Linn"),
    "UMATCOR": ("OR", "Umatilla"),
    "COLUMOR": ("OR", "Columbia"),
    "SPRNGOR": ("OR", "Lane"),
    "BOPSHE": ("OR", "Yamhill"),
    "AKCOOKI": ("AK", "Anchorage"),
    "ANCHOAK": ("AK", "Anchorage"),
    "ANCHOLD": ("AK", "Anchorage"),
    "AKHIGHL": ("AK", "Anchorage"),
    "AKLEMON": ("AK", "Juneau"),
    "SITKAAK": ("AK", "Sitka"),
    "AKKETCH": ("AK", "Ketchikan Gateway"),
    "AKFAIRB": ("AK", "Fairbanks North Star"),
    "AKPALMC": ("AK", "Matanuska-Susitna"),
    "AKWILPT": ("AK", "Kenai Peninsula"),
    "AKWILCC": ("AK", "Kenai Peninsula"),
    "AKGSCCC": ("AK", "Matanuska-Susitna"),
    "KODIAAK": ("AK", "Kodiak Island"),
    "BOPHON": ("HI", "Honolulu"),
    "HHWHOLD": ("HI", "Honolulu"),
    "PMMCAHI": ("HI", "Honolulu"),
    "AGC": ("PR", "Aguadilla"),
    "SJS": ("PR", "Bayamon"),
    "BOPGUA": ("PR", "Guaynabo"),
    "BAYAMPR": ("PR", "Bayamon"),
    "PAVHRPR": ("PR", "San Juan"),
    "HOSPSPR": ("PR", "San Juan"),
    "CMEDHPR": ("PR", "Bayamon"),
    "PRVEGAL": ("PR", "Vega Alta"),
    "AIRHOPR": ("PR", "Carolina"),
    "SAJHOLD": ("PR", "San Juan"),
    "SJUHOLD": ("PR", "Carolina"),
    "GUDOCHG": ("GU", "Guam"),
    "DEPCOGU": ("GU", "Guam"),
    "AGAHOLD": ("GU", "Guam"),
    "STTCJVI": ("VI", "St. Thomas"),
    "CHAHOLD": ("VI", "St. Thomas"),
    "MPSIPAN": ("MP", "Saipan"),
    "SAIHOLD": ("MP", "Saipan"),
    "BOPDAL": ("TX", "Childress"),
    "BOPMCR": ("KY", "McCreary"),
    "BOPTRV": ("TX", "Live Oak"),
    "BOPVIM": ("CA", "San Bernardino"),
    "BOPSDC": ("CA", "San Diego"),
    "BOPSPG": ("MO", "Greene"),
    "BOPGIL": ("WV", "Gilmer"),
    "BOPALM": ("PA", "Union"),
    "BOPTHA": ("IN", "Vigo"),
    "BOPPOL": ("LA", "Grant"),
    "BOPLEM": ("PA", "Union"),
    "BOPRBK": ("NY", "Essex"),
    "BOPPET": ("VA", "Dinwiddie"),
    "DESERFL": ("FL", "Polk"),
    "WINWYAZ": ("AZ", "Pinal"),
    "RDRVHTX": ("TX", "Wichita"),
    "PKLDHTX": ("TX", "Dallas"),
    "LAURITX": ("TX", "Bexar"),
    "PLMBHTX": ("TX", "Bexar"),
    "LIMMCTX": ("TX", "Limestone"),
    "LIMESTX": ("TX", "Limestone"),
    "LIMCJTX": ("TX", "Limestone"),
    "WOAKSTX": ("TX", "Harris"),
    "RVBHHTX": ("TX", "El Paso"),
    "LRDMCTX": ("TX", "Webb"),
    "ASWHRTX": ("TX", "Williamson"),
    "CCHRTTX": ("TX", "Bell"),
    "BFGHITX": ("TX", "Bexar"),
    "TRYOSCA": ("CA", "San Bernardino"),
    "NIXHCTX": ("TX", "Bexar"),
    "LLUMCCA": ("CA", "San Bernardino"),
    "GSAMHCA": ("CA", "Los Angeles"),
    "CWHCCMP": ("MP", "Saipan"),
    "PIERCND": ("ND", "Pierce"),
    "GFCORND": ("ND", "Grand Forks"),
    "GRFHOLD": ("ND", "Grand Forks"),
    "GFJUVND": ("ND", "Grand Forks"),
    "WARDCND": ("ND", "Ward"),
    "BURLEND": ("ND", "Burleigh"),
    "STUTSND": ("ND", "Stutsman"),
    "CASSCND": ("ND", "Cass"),
    "BOTTIND": ("ND", "Bottineau"),
    "MOUNTND": ("ND", "Mountrail"),
    "WALSHND": ("ND", "Walsh"),
    "HACTCND": ("ND", "Cass"),
    "PENNISD": ("SD", "Pennington"),
    "RPCHOLD": ("SD", "Pennington"),
    "MINNESD": ("SD", "Minnehaha"),
    "SFDHOLD": ("SD", "Minnehaha"),
    "ROBERSD": ("SD", "Roberts"),
    "MEADESD": ("SD", "Meade"),
    "YANCOSD": ("SD", "Yankton"),
    "BROWNSD": ("SD", "Brown"),
    "UNIONSD": ("SD", "Union"),
    "TURNESD": ("SD", "Turner"),

    "NCWESDF": ("NC", "Anson"),
    "GRRHOLD": ("SC", "Greenville"),
}


KNOWN_NAME_KEYWORDS: list[tuple[str, str, str]] = [
    (r"PORT\s+ISABEL", "TX", "Cameron"),
    (r"FLORENCE\s+(SPC|STAGING|SERVICE)", "AZ", "Pinal"),
    (r"ELOY", "AZ", "Pinal"),
    (r"\bELOY\b", "AZ", "Pinal"),
    (r"ADELANTO", "CA", "San Bernardino"),
    (r"OTAY\s+MESA", "CA", "San Diego"),
    (r"MESA\s+VERDE", "CA", "Kern"),
    (r"GOLDEN\s+STATE\s+ANNEX", "CA", "Kern"),
    (r"DESERT\s+VIEW\s+ANNEX", "CA", "Kern"),
    (r"\bDILLEY\b", "TX", "Frio"),
    (r"PEARSALL", "TX", "Frio"),
    (r"SOUTH\s+TEXAS\s+(ICE|FAM)", "TX", "Frio"),
    (r"KARNES", "TX", "Karnes"),
    (r"JOE\s+CORLEY", "TX", "Montgomery"),
    (r"IAH\s+SECURE", "TX", "Polk"),
    (r"\bPOLK\b", "TX", "Polk"),
    (r"ALEXANDRIA\s+STAGING", "LA", "Rapides"),
    (r"OAKDALE", "LA", "Allen"),
    (r"PINE\s+PRAIRIE", "LA", "Evangeline"),
    (r"\bJENA\b", "LA", "LaSalle"),
    (r"WINNFIELD|\bWINN\s+CORR", "LA", "Winn"),
    (r"RICHWOOD", "LA", "Ouachita"),
    (r"BASILE", "LA", "Acadia"),
    (r"STEWART\s+DETENTION", "GA", "Stewart"),
    (r"FOLKSTON", "GA", "Charlton"),
    (r"IRWIN\s+COUNTY", "GA", "Irwin"),
    (r"MOSHANNON", "PA", "Clearfield"),
    (r"BERKS\s+COUNTY", "PA", "Berks"),
    (r"YORK\s+COUNTY\s+(JAIL|PRISON|DET).*PA", "PA", "York"),
    (r"BUFFALO\s+SPC|BATAVIA", "NY", "Genesee"),
    (r"VARICK", "NY", "New York"),
    (r"VARRICK", "NY", "New York"),
    (r"ELIZABETH\s+CONTRACT", "NJ", "Union"),
    (r"DELANEY\s+HALL", "NJ", "Essex"),
    (r"BOSTON\s+SPC", "MA", "Suffolk"),
    (r"PLYMOUTH\s+CO", "MA", "Plymouth"),
    (r"BRISTOL.*DARTMOUTH", "MA", "Bristol"),
    (r"KROME", "FL", "Miami-Dade"),
    (r"BROWARD\s+TRANSITIONAL", "FL", "Broward"),
    (r"GLADES\s+COUNTY|GLADES\s+DET", "FL", "Glades"),
    (r"WAKULLA", "FL", "Wakulla"),
    (r"CIBOLA", "NM", "Cibola"),
    (r"OTERO\s+(CO|COUNTY|PROCESSING)", "NM", "Otero"),
    (r"TORRANCE.*\bNM\b|TORRANCE/ESTANCIA", "NM", "Torrance"),
    (r"NW\s+ICE\s+PROCESSING|NORTHWEST\s+ICE\s+PROC|TACOMA", "WA", "Pierce"),
    (r"PRAIRIELAND", "TX", "Johnson"),
    (r"BLUEBONNET\s+DET", "TX", "Anderson"),
    (r"COASTAL\s+BEND", "TX", "Nueces"),
    (r"SAN\s+LUIS\s+REGIONAL", "AZ", "Yuma"),
    (r"WEST\s+TEXAS\s+DET", "TX", "Hudspeth"),
    (r"MONTGOMERY\s+CO.*JAIL|MONTGOMERY\s+PROCESSING", "TX", "Montgomery"),
    (r"VAL\s+VERDE", "TX", "Val Verde"),
    (r"WILLACY", "TX", "Willacy"),
    (r"\bRAYMONDVILLE\b", "TX", "Willacy"),
    (r"EAST\s+HIDALGO", "TX", "Hidalgo"),
    (r"RIO\s+GRANDE\s+DET", "TX", "Webb"),
    (r"LAREDO\s+(PROC|DET)", "TX", "Webb"),
    (r"BROOKS\s+COUNTY", "TX", "Brooks"),
    (r"LA\s+SALLE\s+CO\s+REG", "TX", "La Salle"),
    (r"HASKELL\s+CO|ROLLING\s+PLAINS", "TX", "Haskell"),
    (r"RIO\s+GRANDE\s+VALLEY\s+STAGING", "TX", "Hidalgo"),
    (r"\bDIMMIT\s+REG", "TX", "Dimmit"),
    (r"\bWEBB\s+CO", "TX", "Webb"),
    (r"\bHUDSPETH\b", "TX", "Hudspeth"),
    (r"GUAM", "GU", "Guam"),
    (r"SAIPAN", "MP", "Saipan"),
    (r"AGUADILLA", "PR", "Aguadilla"),
    (r"VEGA\s+ALTA", "PR", "Vega Alta"),
    (r"BAYAMON", "PR", "Bayamon"),
    (r"GUAYNABO", "PR", "Guaynabo"),
]


CITY_COUNTY_HINTS: dict[str, tuple[str, str]] = {
    "DALLAS": ("TX", "Dallas"),
    "HOUSTON": ("TX", "Harris"),
    "SAN ANTONIO": ("TX", "Bexar"),
    "AUSTIN": ("TX", "Travis"),
    "EL PASO": ("TX", "El Paso"),
    "HARLINGEN": ("TX", "Cameron"),
    "PORT ISABEL": ("TX", "Cameron"),
    "BROWNSVILLE": ("TX", "Cameron"),
    "MCALLEN": ("TX", "Hidalgo"),
    "EDINBURG": ("TX", "Hidalgo"),
    "LAREDO": ("TX", "Webb"),
    "PEARSALL": ("TX", "Frio"),
    "DILLEY": ("TX", "Frio"),
    "CONROE": ("TX", "Montgomery"),
    "AMARILLO": ("TX", "Potter"),
    "LUBBOCK": ("TX", "Lubbock"),
    "MIDLAND": ("TX", "Midland"),
    "ABILENE": ("TX", "Taylor"),
    "SAN ANGELO": ("TX", "Tom Green"),
    "WACO": ("TX", "McLennan"),
    "EULESS": ("TX", "Tarrant"),
    "BEDFORD": ("TX", "Tarrant"),
    "FORT WORTH": ("TX", "Tarrant"),
    "PECOS": ("TX", "Reeves"),
    "ODESSA": ("TX", "Ector"),
    "CORPUS CHRISTI": ("TX", "Nueces"),
    "VICTORIA": ("TX", "Victoria"),
    "DEL RIO": ("TX", "Val Verde"),
    "BIG SPRING": ("TX", "Howard"),
    "BIG SPRINGS": ("TX", "Howard"),
    "TYLER": ("TX", "Smith"),
    "BEAUMONT": ("TX", "Jefferson"),
    "GALVESTON": ("TX", "Galveston"),
    "RAYMONDVILLE": ("TX", "Willacy"),
    "LIVINGSTON": ("TX", "Polk"),
    "EAGLE PASS": ("TX", "Maverick"),
    "ATHENS": ("TX", "Henderson"),
    "ALBUQUERQUE": ("NM", "Bernalillo"),
    "LAS CRUCES": ("NM", "Dona Ana"),
    "ROSWELL": ("NM", "Chaves"),
    "ARTESIA": ("NM", "Eddy"),
    "SANTA FE": ("NM", "Santa Fe"),
    "PHOENIX": ("AZ", "Maricopa"),
    "TUCSON": ("AZ", "Pima"),
    "FLORENCE": ("AZ", "Pinal"),
    "ELOY": ("AZ", "Pinal"),
    "YUMA": ("AZ", "Yuma"),
    "CASA GRANDE": ("AZ", "Pinal"),
    "FLAGSTAFF": ("AZ", "Coconino"),
    "MESA": ("AZ", "Maricopa"),
    "SCOTTSDALE": ("AZ", "Maricopa"),
    "TEMPE": ("AZ", "Maricopa"),
    "LOS ANGELES": ("CA", "Los Angeles"),
    "SAN DIEGO": ("CA", "San Diego"),
    "SAN FRANCISCO": ("CA", "San Francisco"),
    "SAN JOSE": ("CA", "Santa Clara"),
    "SACRAMENTO": ("CA", "Sacramento"),
    "FRESNO": ("CA", "Fresno"),
    "BAKERSFIELD": ("CA", "Kern"),
    "STOCKTON": ("CA", "San Joaquin"),
    "OAKLAND": ("CA", "Alameda"),
    "SAN BERNARDINO": ("CA", "San Bernardino"),
    "RIVERSIDE": ("CA", "Riverside"),
    "VENTURA": ("CA", "Ventura"),
    "SANTA ANA": ("CA", "Orange"),
    "WESTMINSTER": ("CA", "Orange"),
    "ANAHEIM": ("CA", "Orange"),
    "EL CENTRO": ("CA", "Imperial"),
    "REDDING": ("CA", "Shasta"),
    "ADELANTO": ("CA", "San Bernardino"),
    "LANCASTER": ("CA", "Los Angeles"),
    "BLYTHE": ("CA", "Riverside"),
    "CALEXICO": ("CA", "Imperial"),
    "CALIPATRIA": ("CA", "Imperial"),
    "LOMPOC": ("CA", "Santa Barbara"),
    "VICTORVILLE": ("CA", "San Bernardino"),
    "MIAMI": ("FL", "Miami-Dade"),
    "ORLANDO": ("FL", "Orange"),
    "TAMPA": ("FL", "Hillsborough"),
    "JACKSONVILLE": ("FL", "Duval"),
    "TALLAHASSEE": ("FL", "Leon"),
    "FORT MYERS": ("FL", "Lee"),
    "FT MYERS": ("FL", "Lee"),
    "PENSACOLA": ("FL", "Escambia"),
    "BRADENTON": ("FL", "Manatee"),
    "WEST PALM BEACH": ("FL", "Palm Beach"),
    "STUART": ("FL", "Martin"),
    "MIRAMAR": ("FL", "Broward"),
    "FOLKSTON": ("GA", "Charlton"),
    "MOORE HAVEN": ("FL", "Glades"),
    "DANIA BEACH": ("FL", "Broward"),
    "ATLANTA": ("GA", "Fulton"),
    "SAVANNAH": ("GA", "Chatham"),
    "GAINESVILLE": ("GA", "Hall"),
    "MACON": ("GA", "Bibb"),
    "DALTON": ("GA", "Whitfield"),
    "STEWART": ("GA", "Stewart"),
    "BIRMINGHAM": ("AL", "Jefferson"),
    "MOBILE": ("AL", "Mobile"),
    "MONTGOMERY": ("AL", "Montgomery"),
    "ETOWAH": ("AL", "Etowah"),
    "JACKSON": ("MS", "Hinds"),
    "GULFPORT": ("MS", "Harrison"),
    "ADAMS": ("MS", "Adams"),
    "NEW ORLEANS": ("LA", "Orleans"),
    "BATON ROUGE": ("LA", "East Baton Rouge"),
    "ALEXANDRIA": ("LA", "Rapides"),
    "JENA": ("LA", "LaSalle"),
    "WINN": ("LA", "Winn"),
    "WINNFIELD": ("LA", "Winn"),
    "OAKDALE": ("LA", "Allen"),
    "PINE PRAIRIE": ("LA", "Evangeline"),
    "RICHWOOD": ("LA", "Ouachita"),
    "LAFAYETTE": ("LA", "Lafayette"),
    "SHREVEPORT": ("LA", "Caddo"),
    "MONROE": ("LA", "Ouachita"),
    "NEW YORK": ("NY", "New York"),
    "MANHATTAN": ("NY", "New York"),
    "BUFFALO": ("NY", "Erie"),
    "BATAVIA": ("NY", "Genesee"),
    "ALBANY": ("NY", "Albany"),
    "SYRACUSE": ("NY", "Onondaga"),
    "ROCHESTER": ("NY", "Monroe"),
    "FISHKILL": ("NY", "Dutchess"),
    "RAY BROOK": ("NY", "Essex"),
    "BROOKLYN": ("NY", "Kings"),
    "BRONX": ("NY", "Bronx"),
    "QUEENS": ("NY", "Queens"),
    "STATEN ISLAND": ("NY", "Richmond"),
    "CHAMPLAIN": ("NY", "Clinton"),
    "RIKERS": ("NY", "Bronx"),
    "WHITE PLAINS": ("NY", "Westchester"),
    "CENTRAL ISLIP": ("NY", "Suffolk"),
    "LONG ISLAND": ("NY", "Suffolk"),
    "NEWBURGH": ("NY", "Orange"),
    "ELIZABETH": ("NJ", "Union"),
    "NEWARK": ("NJ", "Essex"),
    "JERSEY CITY": ("NJ", "Hudson"),
    "BERGEN": ("NJ", "Bergen"),
    "ESSEX": ("NJ", "Essex"),
    "HUDSON": ("NJ", "Hudson"),
    "MOUNT LAUREL": ("NJ", "Burlington"),
    "MT. LAUREL": ("NJ", "Burlington"),
    "MT LAUREL": ("NJ", "Burlington"),
    "PHILADELPHIA": ("PA", "Philadelphia"),
    "PITTSBURGH": ("PA", "Allegheny"),
    "PITTSBURG": ("PA", "Allegheny"),
    "YORK": ("PA", "York"),
    "WILLIAMSPORT": ("PA", "Lycoming"),
    "ALLENTOWN": ("PA", "Lehigh"),
    "ERIE": ("PA", "Erie"),
    "BALTIMORE": ("MD", "Baltimore city"),
    "WASHINGTON": ("DC", "District of Columbia"),
    "RICHMOND": ("VA", "Richmond city"),
    "ROANOKE": ("VA", "Roanoke city"),
    "NORFOLK": ("VA", "Norfolk city"),
    "ALEXANDRIA, VA": ("VA", "Alexandria city"),
    "FARMVILLE": ("VA", "Prince Edward"),
    "HARRISONBURG": ("VA", "Harrisonburg city"),
    "FAIRFAX": ("VA", "Fairfax"),
    "VIRGINIA BEACH": ("VA", "Virginia Beach city"),
    "BOSTON": ("MA", "Suffolk"),
    "WORCESTER": ("MA", "Worcester"),
    "SPRINGFIELD, MA": ("MA", "Hampden"),
    "BRIDGEWATER": ("MA", "Plymouth"),
    "BARNSTABLE": ("MA", "Barnstable"),
    "HARTFORD": ("CT", "Hartford"),
    "NEW HAVEN": ("CT", "New Haven"),
    "PROVIDENCE": ("RI", "Providence"),
    "MANCHESTER": ("NH", "Hillsborough"),
    "DOVER, NH": ("NH", "Strafford"),
    "ST. ALBANS": ("VT", "Franklin"),
    "ST ALBANS": ("VT", "Franklin"),
    "BURLINGTON, VT": ("VT", "Chittenden"),
    "PORTLAND, ME": ("ME", "Cumberland"),
    "BANGOR": ("ME", "Penobscot"),
    "DOVER": ("DE", "Kent"),
    "WILMINGTON, DE": ("DE", "New Castle"),
    "SEATTLE": ("WA", "King"),
    "TACOMA": ("WA", "Pierce"),
    "SPOKANE": ("WA", "Spokane"),
    "RICHLAND": ("WA", "Benton"),
    "WENATCHEE": ("WA", "Chelan"),
    "YAKIMA": ("WA", "Yakima"),
    "FERNDALE": ("WA", "Whatcom"),
    "BELLINGHAM": ("WA", "Whatcom"),
    "PORTLAND, OR": ("OR", "Multnomah"),
    "PORTLAND": ("OR", "Multnomah"),
    "EUGENE": ("OR", "Lane"),
    "SALEM": ("OR", "Marion"),
    "MEDFORD": ("OR", "Jackson"),
    "BEND": ("OR", "Deschutes"),
    "SHERIDAN": ("OR", "Yamhill"),
    "BOISE": ("ID", "Ada"),
    "TWIN FALLS": ("ID", "Twin Falls"),
    "IDAHO FALLS": ("ID", "Bonneville"),
    "SALT LAKE CITY": ("UT", "Salt Lake"),
    "PROVO": ("UT", "Utah"),
    "OGDEN": ("UT", "Weber"),
    "ST. GEORGE": ("UT", "Washington"),
    "ST GEORGE": ("UT", "Washington"),
    "LAS VEGAS": ("NV", "Clark"),
    "RENO": ("NV", "Washoe"),
    "HENDERSON": ("NV", "Clark"),
    "PAHRUMP": ("NV", "Nye"),
    "CHEYENNE": ("WY", "Laramie"),
    "CASPER": ("WY", "Natrona"),
    "CASPAR": ("WY", "Natrona"),
    "BILLINGS": ("MT", "Yellowstone"),
    "HELENA": ("MT", "Lewis and Clark"),
    "MISSOULA": ("MT", "Missoula"),
    "GREAT FALLS": ("MT", "Cascade"),
    "DENVER": ("CO", "Denver"),
    "AURORA": ("CO", "Adams"),
    "COLORADO SPRINGS": ("CO", "El Paso"),
    "GRAND JUNCTION": ("CO", "Mesa"),
    "PUEBLO": ("CO", "Pueblo"),
    "GLENWOOD SPRINGS": ("CO", "Garfield"),
    "ALAMOSA": ("CO", "Alamosa"),
    "DURANGO": ("CO", "La Plata"),
    "CRAIG": ("CO", "Moffat"),
    "LOVELAND": ("CO", "Larimer"),
    "BRUSH": ("CO", "Morgan"),
    "FREDERICK": ("CO", "Weld"),
    "FORT COLLINS": ("CO", "Larimer"),
    "FARGO": ("ND", "Cass"),
    "GRAND FORKS": ("ND", "Grand Forks"),
    "BISMARCK": ("ND", "Burleigh"),
    "MINOT": ("ND", "Ward"),
    "RAPID CITY": ("SD", "Pennington"),
    "SIOUX FALLS": ("SD", "Minnehaha"),
    "SIOUX CITY": ("IA", "Woodbury"),
    "ABERDEEN": ("SD", "Brown"),
    "OMAHA": ("NE", "Douglas"),
    "LINCOLN": ("NE", "Lancaster"),
    "GRAND ISLAND": ("NE", "Hall"),
    "NORTH PLATTE": ("NE", "Lincoln"),
    "DES MOINES": ("IA", "Polk"),
    "CEDAR RAPIDS": ("IA", "Linn"),
    "DAVENPORT": ("IA", "Scott"),
    "MINNEAPOLIS": ("MN", "Hennepin"),
    "ST. PAUL": ("MN", "Ramsey"),
    "ST PAUL": ("MN", "Ramsey"),
    "DULUTH": ("MN", "St. Louis"),
    "ROCHESTER, MN": ("MN", "Olmsted"),
    "MILWAUKEE": ("WI", "Milwaukee"),
    "MADISON": ("WI", "Dane"),
    "GREEN BAY": ("WI", "Brown"),
    "KENOSHA": ("WI", "Kenosha"),
    "WAUKESHA": ("WI", "Waukesha"),
    "JUNEAU, WI": ("WI", "Dodge"),
    "CHICAGO": ("IL", "Cook"),
    "BROADVIEW": ("IL", "Cook"),
    "ROCKFORD": ("IL", "Winnebago"),
    "ROCK ISLAND": ("IL", "Rock Island"),
    "PEORIA": ("IL", "Peoria"),
    "SPRINGFIELD, IL": ("IL", "Sangamon"),
    "ELGIN": ("IL", "Cook"),
    "INDIANAPOLIS": ("IN", "Marion"),
    "FORT WAYNE": ("IN", "Allen"),
    "EVANSVILLE": ("IN", "Vanderburgh"),
    "COLUMBUS": ("OH", "Franklin"),
    "CLEVELAND": ("OH", "Cuyahoga"),
    "CINCINNATI": ("OH", "Hamilton"),
    "TOLEDO": ("OH", "Lucas"),
    "DAYTON": ("OH", "Montgomery"),
    "AKRON": ("OH", "Summit"),
    "YOUNGSTOWN": ("OH", "Mahoning"),
    "DETROIT": ("MI", "Wayne"),
    "GRAND RAPIDS": ("MI", "Kent"),
    "LANSING": ("MI", "Ingham"),
    "ANN ARBOR": ("MI", "Washtenaw"),
    "BATTLE CREEK": ("MI", "Calhoun"),
    "MONROE, MI": ("MI", "Monroe"),
    "LOUISVILLE": ("KY", "Jefferson"),
    "LEXINGTON": ("KY", "Fayette"),
    "BOWLING GREEN": ("KY", "Warren"),
    "NASHVILLE": ("TN", "Davidson"),
    "MEMPHIS": ("TN", "Shelby"),
    "KNOXVILLE": ("TN", "Knox"),
    "CHATTANOOGA": ("TN", "Hamilton"),
    "CHATANOOGA": ("TN", "Hamilton"),
    "RALEIGH": ("NC", "Wake"),
    "CHARLOTTE": ("NC", "Mecklenburg"),
    "GREENSBORO": ("NC", "Guilford"),
    "WILMINGTON": ("NC", "New Hanover"),
    "DURHAM": ("NC", "Durham"),
    "ASHEVILLE": ("NC", "Buncombe"),
    "FAYETTEVILLE, NC": ("NC", "Cumberland"),
    "HENDERSONVILLE": ("NC", "Henderson"),
    "CHARLESTON": ("SC", "Charleston"),
    "COLUMBIA": ("SC", "Richland"),
    "GREENVILLE": ("SC", "Greenville"),
    "GREER": ("SC", "Greenville"),
    "LITTLE ROCK": ("AR", "Pulaski"),
    "FAYETTEVILLE": ("AR", "Washington"),
    "FORT SMITH": ("AR", "Sebastian"),
    "TEXARKANA": ("AR", "Miller"),
    "ST. LOUIS": ("MO", "St. Louis city"),
    "ST LOUIS": ("MO", "St. Louis city"),
    "KANSAS CITY": ("MO", "Jackson"),
    "KANSAS": ("MO", "Jackson"),
    "VARRICK": ("NY", "New York"),
    "VARICK": ("NY", "New York"),
    "MOUNT LAUREL NJ": ("NJ", "Burlington"),
    "HUNTSVILLE": ("TX", "Walker"),
    "CASPER": ("WY", "Natrona"),
    "SPRINGFIELD": ("MO", "Greene"),
    "SPRINGFIELD, MO": ("MO", "Greene"),
    "WICHITA": ("KS", "Sedgwick"),
    "TOPEKA": ("KS", "Shawnee"),
    "GARDEN CITY": ("KS", "Finney"),
    "OKLAHOMA CITY": ("OK", "Oklahoma"),
    "TULSA": ("OK", "Tulsa"),
    "OK CITY": ("OK", "Oklahoma"),
    "ANCHORAGE": ("AK", "Anchorage"),
    "FAIRBANKS": ("AK", "Fairbanks North Star"),
    "JUNEAU": ("AK", "Juneau"),
    "SITKA": ("AK", "Sitka"),
    "KETCHIKAN": ("AK", "Ketchikan Gateway"),
    "KODIAK": ("AK", "Kodiak Island"),
    "HONOLULU": ("HI", "Honolulu"),
    "SAN JUAN": ("PR", "San Juan"),
    "AGUADILLA": ("PR", "Aguadilla"),
    "BAYAMON": ("PR", "Bayamon"),
    "AGANA": ("GU", "Guam"),
    "HAGATNA": ("GU", "Guam"),
    "SAIPAN": ("MP", "Saipan"),
    "CHARLOTTE AMALIE": ("VI", "St. Thomas"),
}


_COUNTY_NAME_PATTERNS = [
    re.compile(r"\b([A-Z][A-Z .'-]*?)\s+CO(?:UNTY|\.|)\s+(?:SHERIFF|JAIL|DET|CORR|REGIONAL|JUSTICE)"),
    re.compile(r"\b([A-Z][A-Z .'-]*?)\s+CO(?:UNTY|\.|)\s+J\b"),
]


def _normalize_county(raw: str) -> str:
    s = raw.strip().rstrip(".,").strip()
    s = re.sub(r"\s+(JAIL|SHERIFF|DET|CORR|REGIONAL|JUSTICE)\b.*$", "", s)
    return s.title()


def _extract_county_from_pattern(name: str) -> str | None:
    upper = name.upper()
    for pat in _COUNTY_NAME_PATTERNS:
        m = pat.search(upper)
        if m:
            return _normalize_county(m.group(1))
    return None


def lookup_city_county(city: str) -> tuple[str, str] | None:
    if not city:
        return None
    upper = city.upper().strip()
    if upper in CITY_COUNTY_HINTS:
        return CITY_COUNTY_HINTS[upper]
    for key in sorted(CITY_COUNTY_HINTS, key=len, reverse=True):
        if re.search(rf"\b{re.escape(key)}\b", upper):
            return CITY_COUNTY_HINTS[key]
    return None


_DECORATION_WORDS = ("county", "parish", "borough", "municipality")
_DECORATION_PREFIXES = sorted(
    {w[:n] for w in _DECORATION_WORDS for n in range(1, len(w) + 1)},
    key=len, reverse=True,
)
# FIPS reference truncates county names at 16 chars.
_DECORATION_RE = re.compile(
    r"\s+(?:" + "|".join(_DECORATION_PREFIXES) + r"|census area|city and borough)$"
)


def norm_county(s: str) -> str:
    if s is None:
        return ""
    s = s.strip().lower().replace(".", "").replace(",", "")
    s = " ".join(s.split())
    prev = None
    while prev != s:
        prev = s
        s = _DECORATION_RE.sub("", s)
    return s


def norm_compact(s: str) -> str:
    return norm_county(s).replace(" ", "").replace("-", "").replace("'", "")


def county_token_from_name(name: str) -> str | None:
    """If a name contains '<X> COUNTY', return normalized X, else None.

    Walks backward from ' COUNTY' and stops at the nearest separator
    (comma, slash, ' - ') so an agency prefix like 'ERO - PIKE COUNTY'
    yields 'pike', not 'ero - pike'. Deterministic; never invents a state.
    """
    up = (name or "").upper()
    idx = up.find(" COUNTY")
    if idx == -1:
        return None
    prefix = up[:idx]
    for sep in (",", "/", " - ", " — ", " – "):
        if sep in prefix:
            prefix = prefix.rsplit(sep, 1)[-1]
    tok = norm_county(prefix.strip())
    return tok or None


_USPS = {
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI",
    "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN",
    "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
    "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA",
    "WV", "WI", "WY", "PR", "GU", "VI", "AS", "MP",
}


def resolve_facility(name: str, code: str | None) -> CountyHit | None:
    code_clean = (code or "").strip().upper()
    if code_clean in KNOWN_FACILITY_CODES:
        st, county = KNOWN_FACILITY_CODES[code_clean]
        return CountyHit(st, county, "code")

    upper = (name or "").upper()
    for regex_str, st, county in KNOWN_NAME_KEYWORDS:
        if re.search(regex_str, upper):
            return CountyHit(st, county, "name")

    code_state = ""
    if code_clean and len(code_clean) >= 2 and code_clean[-2:].isalpha():
        candidate = code_clean[-2:]
        if candidate in _USPS:
            code_state = candidate

    extracted = _extract_county_from_pattern(upper)
    if extracted and code_state:
        return CountyHit(code_state, extracted, "county_jail_pattern")

    for city in sorted(CITY_COUNTY_HINTS, key=len, reverse=True):
        if re.search(rf"\b{re.escape(city)}\b", upper):
            st, county = CITY_COUNTY_HINTS[city]
            if code_state and code_state != st:
                continue
            return CountyHit(st, county, "city")

    return None
